Repository Shiwankar-Mrunal/Terraform-Microservices-Pipeline, pull requests merged in 2025-10, with the labels that each got.

#3 add test cases
  ci-app/test_app.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2025

#18 Initial commit
  Terraform_pipeline/main.tf
  Terraform_pipeline/modules/webapp.tf
Labels: hacktoberfest-accepted, hacktoberfest2025

#20 Initial commit
  Terraform_pipeline/main.tf
Labels: hacktoberfest-accepted, hacktoberfest2025

#29 Add Working Directory changes
  .github/workflows/Terraform-CICD.yml
Labels: bug, hacktoberfest-accepted, hacktoberfest2025

#30 Fix Main.tf file formatting
  Terraform_pipeline/main.tf
Labels: hacktoberfest-accepted, hacktoberfest2025

#31 Fix Formatting
  Terraform_pipeline/variable.tf
Labels: hacktoberfest-accepted, hacktoberfest2025
